import {
  Link2, Type, Phone, MessageSquare, Mail, Wifi, Contact, IdCard,
  MapPin, CalendarDays, Facebook, Instagram, Music2, Youtube, Linkedin,
  Twitter, Wallet, IndianRupee, Bitcoin, FileText, Smartphone, Video,
  AudioLines, MessageCircle, Send, Globe, Banknote, CreditCard, Landmark, Building2
} from 'lucide-react';

// Each category: id, label, icon, group, fields[], and build(values) -> string encoded in QR
export const CATEGORIES = [
  { id: 'url', label: 'Website URL', icon: Link2, group: 'Basics',
    fields: [{ key: 'url', label: 'Website address', placeholder: 'https://yourbrand.com' }],
    build: v => v.url || '' },
  { id: 'text', label: 'Plain Text', icon: Type, group: 'Basics',
    fields: [{ key: 'text', label: 'Your text', placeholder: 'Anything you like', type: 'textarea' }],
    build: v => v.text || '' },
  { id: 'phone', label: 'Phone Number', icon: Phone, group: 'Contact',
    fields: [{ key: 'phone', label: 'Phone number', placeholder: '+1 555 123 4567' }],
    build: v => `tel:${v.phone || ''}` },
  { id: 'sms', label: 'SMS Message', icon: MessageSquare, group: 'Contact',
    fields: [{ key: 'phone', label: 'Phone number', placeholder: '+1 555 123 4567' }, { key: 'msg', label: 'Message', placeholder: 'Hi there!' }],
    build: v => `SMSTO:${v.phone || ''}:${v.msg || ''}` },
  { id: 'email', label: 'Email', icon: Mail, group: 'Contact',
    fields: [{ key: 'to', label: 'To', placeholder: 'hello@brand.com' }, { key: 'subject', label: 'Subject', placeholder: 'Hello' }, { key: 'body', label: 'Body', placeholder: 'Message', type: 'textarea' }],
    build: v => `mailto:${v.to || ''}?subject=${encodeURIComponent(v.subject || '')}&body=${encodeURIComponent(v.body || '')}` },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageCircle, group: 'Social',
    fields: [{ key: 'phone', label: 'Number (with code)', placeholder: '15551234567' }, { key: 'msg', label: 'Prefilled text', placeholder: 'Hello!' }],
    build: v => `https://wa.me/${(v.phone || '').replace(/\D/g, '')}?text=${encodeURIComponent(v.msg || '')}` },
  { id: 'wifi', label: 'WiFi Access', icon: Wifi, group: 'Basics',
    fields: [{ key: 'ssid', label: 'Network name (SSID)', placeholder: 'MyNetwork' }, { key: 'pass', label: 'Password', placeholder: 'password' }, { key: 'enc', label: 'Security (WPA/WEP/nopass)', placeholder: 'WPA' }],
    build: v => `WIFI:T:${v.enc || 'WPA'};S:${v.ssid || ''};P:${v.pass || ''};;` },
  { id: 'vcard', label: 'vCard Contact', icon: Contact, group: 'Contact',
    fields: [{ key: 'name', label: 'Full name', placeholder: 'Jordan Rivera' }, { key: 'phone', label: 'Phone', placeholder: '+1 555 123 4567' }, { key: 'email', label: 'Email', placeholder: 'jordan@brand.com' }, { key: 'org', label: 'Company', placeholder: 'QRVerse Inc.' }],
    build: v => `BEGIN:VCARD\nVERSION:3.0\nFN:${v.name || ''}\nTEL:${v.phone || ''}\nEMAIL:${v.email || ''}\nORG:${v.org || ''}\nEND:VCARD` },
  { id: 'business', label: 'Business Card', icon: IdCard, group: 'Contact',
    fields: [{ key: 'name', label: 'Name', placeholder: 'Jordan Rivera' }, { key: 'title', label: 'Job title', placeholder: 'Founder' }, { key: 'org', label: 'Company', placeholder: 'QRVerse' }, { key: 'url', label: 'Website', placeholder: 'https://brand.com' }],
    build: v => `BEGIN:VCARD\nVERSION:3.0\nFN:${v.name || ''}\nTITLE:${v.title || ''}\nORG:${v.org || ''}\nURL:${v.url || ''}\nEND:VCARD` },
  { id: 'maps', label: 'Maps Location', icon: MapPin, group: 'Basics',
    fields: [{ key: 'query', label: 'Place or coordinates', placeholder: 'Golden Gate Bridge' }],
    build: v => `https://maps.google.com/?q=${encodeURIComponent(v.query || '')}` },
  { id: 'event', label: 'Event', icon: CalendarDays, group: 'Basics',
    fields: [{ key: 'title', label: 'Event title', placeholder: 'Product Launch' }, { key: 'loc', label: 'Location', placeholder: 'Online' }, { key: 'start', label: 'Start (YYYYMMDDTHHMMSS)', placeholder: '20250101T090000' }, { key: 'end', label: 'End (YYYYMMDDTHHMMSS)', placeholder: '20250101T100000' }],
    build: v => `BEGIN:VEVENT\nSUMMARY:${v.title || ''}\nLOCATION:${v.loc || ''}\nDTSTART:${v.start || ''}\nDTEND:${v.end || ''}\nEND:VEVENT` },
  { id: 'facebook', label: 'Facebook', icon: Facebook, group: 'Social', fields: [{ key: 'url', label: 'Page URL', placeholder: 'https://facebook.com/brand' }], build: v => v.url || '' },
  { id: 'instagram', label: 'Instagram', icon: Instagram, group: 'Social', fields: [{ key: 'user', label: 'Username', placeholder: 'yourbrand' }], build: v => `https://instagram.com/${(v.user || '').replace('@', '')}` },
  { id: 'tiktok', label: 'TikTok', icon: Music2, group: 'Social', fields: [{ key: 'user', label: 'Username', placeholder: 'yourbrand' }], build: v => `https://www.tiktok.com/@${(v.user || '').replace('@', '')}` },
  { id: 'youtube', label: 'YouTube', icon: Youtube, group: 'Social', fields: [{ key: 'url', label: 'Channel or video URL', placeholder: 'https://youtube.com/@brand' }], build: v => v.url || '' },
  { id: 'linkedin', label: 'LinkedIn', icon: Linkedin, group: 'Social', fields: [{ key: 'url', label: 'Profile URL', placeholder: 'https://linkedin.com/in/you' }], build: v => v.url || '' },
  { id: 'twitter', label: 'Twitter / X', icon: Twitter, group: 'Social', fields: [{ key: 'user', label: 'Handle', placeholder: 'yourbrand' }], build: v => `https://x.com/${(v.user || '').replace('@', '')}` },
  { id: 'paypal', label: 'PayPal', icon: Wallet, group: 'Payments', fields: [{ key: 'user', label: 'PayPal.me name', placeholder: 'yourname' }], build: v => `https://paypal.me/${v.user || ''}` },
  { id: 'upi', label: 'UPI Payment', icon: IndianRupee, group: 'Payments', fields: [{ key: 'vpa', label: 'UPI ID', placeholder: 'name@bank' }, { key: 'name', label: 'Payee name', placeholder: 'Jordan' }, { key: 'amt', label: 'Amount', placeholder: '100' }], build: v => `upi://pay?pa=${v.vpa || ''}&pn=${encodeURIComponent(v.name || '')}&am=${v.amt || ''}` },
  { id: 'crypto', label: 'Crypto Wallet', icon: Bitcoin, group: 'Payments', fields: [{ key: 'coin', label: 'Coin (bitcoin/ethereum)', placeholder: 'bitcoin' }, { key: 'addr', label: 'Wallet address', placeholder: 'bc1q...' }], build: v => `${v.coin || 'bitcoin'}:${v.addr || ''}` },
  { id: 'pdf', label: 'PDF Link', icon: FileText, group: 'Basics', fields: [{ key: 'url', label: 'PDF URL', placeholder: 'https://brand.com/file.pdf' }], build: v => v.url || '' },
  { id: 'app', label: 'App Download', icon: Smartphone, group: 'Basics', fields: [{ key: 'url', label: 'Store URL', placeholder: 'https://apps.apple.com/...' }], build: v => v.url || '' },
  { id: 'zoom', label: 'Zoom Meeting', icon: Video, group: 'Social', fields: [{ key: 'url', label: 'Meeting URL', placeholder: 'https://zoom.us/j/123' }], build: v => v.url || '' },
  { id: 'spotify', label: 'Spotify', icon: AudioLines, group: 'Social', fields: [{ key: 'url', label: 'Track / playlist URL', placeholder: 'https://open.spotify.com/...' }], build: v => v.url || '' },
  { id: 'discord', label: 'Discord', icon: MessageCircle, group: 'Social', fields: [{ key: 'url', label: 'Invite URL', placeholder: 'https://discord.gg/invite' }], build: v => v.url || '' },
  { id: 'telegram', label: 'Telegram', icon: Send, group: 'Social', fields: [{ key: 'user', label: 'Username', placeholder: 'yourbrand' }], build: v => `https://t.me/${(v.user || '').replace('@', '')}` },
  { id: 'custom', label: 'Custom URL', icon: Globe, group: 'Basics', fields: [{ key: 'url', label: 'Any URL scheme', placeholder: 'myapp://open?id=1' }], build: v => v.url || '' },

  // Pakistani wallets & banks
  { id: 'easypaisa', label: 'EasyPaisa', icon: Wallet, group: 'Payments', fields: [{ key: 'acct', label: 'Mobile account number', placeholder: '03XXXXXXXXX' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `EasyPaisa Payment\nAccount: ${v.acct || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'jazzcash', label: 'JazzCash', icon: Wallet, group: 'Payments', fields: [{ key: 'acct', label: 'Mobile account number', placeholder: '03XXXXXXXXX' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `JazzCash Payment\nAccount: ${v.acct || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'nayapay', label: 'NayaPay', icon: CreditCard, group: 'Payments', fields: [{ key: 'handle', label: 'NayaPay ID / @tag', placeholder: '@yourtag' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `NayaPay\nID: ${v.handle || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'sadapay', label: 'SadaPay', icon: CreditCard, group: 'Payments', fields: [{ key: 'iban', label: 'IBAN / account', placeholder: 'PK__SADA________' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `SadaPay\nAccount: ${v.iban || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'ubl', label: 'UBL Bank', icon: Landmark, group: 'Payments', fields: [{ key: 'iban', label: 'IBAN', placeholder: 'PK__UNIL________' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `UBL Bank Transfer\nIBAN: ${v.iban || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'mcb', label: 'MCB Bank', icon: Landmark, group: 'Payments', fields: [{ key: 'iban', label: 'IBAN', placeholder: 'PK__MUCB________' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `MCB Bank Transfer\nIBAN: ${v.iban || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'abl', label: 'Allied Bank (ABL)', icon: Building2, group: 'Payments', fields: [{ key: 'iban', label: 'IBAN', placeholder: 'PK__ABPA________' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `Allied Bank Transfer\nIBAN: ${v.iban || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
  { id: 'meezan', label: 'Meezan Bank', icon: Banknote, group: 'Payments', fields: [{ key: 'iban', label: 'IBAN', placeholder: 'PK__MEZN________' }, { key: 'name', label: 'Account title', placeholder: 'Jordan Rivera' }, { key: 'amt', label: 'Amount (PKR)', placeholder: '1000' }], build: v => `Meezan Bank Transfer\nIBAN: ${v.iban || ''}\nName: ${v.name || ''}\nAmount: PKR ${v.amt || ''}` },
];
